### ISSUE TITLE
JsonData als MQTT Topic?

### ISSUE THREAD

**Issue by regda1986** [KlausLi/Esp-Soyosource-Controller#12]
Hey Klaus,

danke für deine wirklich tolle Arbeit! Könntest vielleicht noch die Json Data als MQTT Topic rausschicken lassen? Quasi so wie bei deinem Epever Controller. :)

Wäre super!

Grüße,
Martin

**Comment by KlausLi** [comment]
wann i dawei ned vertrocknet(vatrickäd) bin :-( !

**Comment by Crash123Crash123** [comment]
Hey Martin,

wenn du eine Haussteuerung (Iobroker, ...) oder so hast, kannst du auf der Oberfläche von Klaus auf "Get Json Data" klicken. Diesen Link frage ich im Iobroker alle 10sek. und teile die Daten den Datenpunkten zu. Somit hast du alles.

@KlausLi Im Netz kursiert noch so eine ähnliche Lösung mittels ESPHOME und darin wird auch die Temperatur des Wechselrichters abgefragt. Könntest du das eventuell im Json String mit ausgeben? Gerade im Sommer wäre es interessant, wenn das Gerät heiß wird und somit Leistung abgibt.

**Comment by KlausLi** [comment]
@regda1986  das mit dem mqtt topic alle sekunde rausschicken ist für mich derzeit performance technisch eine unbekanne, müsste ich erst testen.

@Crash123Crash123  Ja die liebe Temperatur , kann ich mich noch erinnern warum ich die nicht implementiert hab... die an rs485 ausgegebene Temperatur ist nicht extakt die gleiche wie am Display angezeigte, das  verwirrt.

... die gemessene AC Spannung ist sowieso erfunden.
Das sind die 2 Sachen die mich am Soyo stören :-)

**Comment by Crash123Crash123** [comment]
@KlausLi Ok. Danke. Dann brauch ich die Temp. nicht.
