### ISSUE TITLE
Probleme Neu-Installation 1.0.1.9 bzw. Update

### ISSUE THREAD

**Issue by Crash123Crash123** [KlausLi/Esp-Soyosource-Controller#13]
Guten Morgen,

ich wollte bei einem bekannten auch deine Super - Lösung umsetzen. Wenn ich jetzt die V1.0.1.9.bin auf dem ESP spiele, kann ich mich nicht drauf verbinden wie früher in V1.0.1.4. Ist die V1.0.1.9 nur ein Update oder der gesamte Code, da mir diese Datei auch deutlich kleiner vorkommt....

Weiters schaffe ich bei folgender Version 1.0.1.4 fix-TZ part2 kein Update auf 1.0.1.9. Upload läuft durch aber es ändert sich nichts, auch nach einen Neustart. Ist jetzt kein großes Problem wäre aber natürlich gern up to date.

**Comment by KlausLi** [comment]
Hallo 
- Firmware ist stetig gewachsen , der Stuhlgang(Code) ist nicht weniger geworden.

- Upgrade Firmware : schalte mal auf NOTAUS  in der ESP GUI und versuchs nochmal(evtl. sind nicht alle bedingungen ideal)
- v1.0.1.9  Standalone auf frischen(gelöschten) esp flashen und verbinden klappt nicht ? Was genau, geht nicht  ?

**Comment by Crash123Crash123** [comment]
Bei V1.0.1.9 auf neuem ESP geflasht wird dann kein AccessPoint aufgebaut, sodass man keine Wlan-Daten eingeben kann.

**Comment by KlausLi** [comment]
das stimmt nicht , ich hab mich nun dazu verleiten lassen es in 2 varianten zu testen 
1. mit tasmotizer , damits sicher ist  mit löschen funktion die firmware geflasht 
2. dann ap auf gemacht , alles wie gehabt und verbunden 
das ganze habe ich 2 mal gemacht einmal mit laptop und google chrome wlan daten eingegeben und einmal mit android tel 

kommt schon freunde , solche behauptungen aufstellen da muss man sich schon sehr sicher sein !
Bitte such den fehler bei deinem esp

**Comment by KlausLi** [comment]
![image](https://user-images.githubusercontent.com/32024629/141986277-85f66308-8dfa-4e26-97d6-ef5e68ef94ad.png)
