### ISSUE TITLE
Funktionert, aber keine Spannungswerte

### ISSUE THREAD

**Issue by evoxievoxi** [KlausLi/Esp-Soyosource-Controller#15]
Hallo vielen Dank für die Programmierung.

Der ESP Herzschlag empfängt die Werte vom Shelly 3EM und sendet auch die richtigen Werte an den Soyo. Leider bekomm ich keine Anzeige von Spannung, Ampere, Leistung. Hat wer eine Idee woran das liegen könnte? Verwendet wird RS485 ttl Adapter.

![ESP](https://user-images.githubusercontent.com/99738696/154103181-bdb101a8-87ed-4cf0-bc25-34cfac1a574b.JPG)

**Comment by evoxievoxi** [comment]
Hier der Link:
https://de.aliexpress.com/item/4001054628033.html?gatewayAdapt=glo2deu&spm=a2g0o.9042311.0.0.45e94c4dkzZ19n

**Comment by KlausLi** [comment]
ich habe 2 hier bestellt , sind jetzt aber teurer 
https://de.aliexpress.com/item/4000250383524.html?gatewayAdapt=glo2deu&spm=a2g0o.9042311.0.0.27424c4dAvXA5N

220v, 48v mit limiter  (evtl macht die limiter option was aus )

**Comment by evoxievoxi** [comment]
wie haben 2# bestellt mit ein paar Monaten Zeitunterschied. Vom selben Lieferanten. Softwarestand ist der selbe. Hardware schwer zu sagen. Aber gut. Habe jetzt einen Shelly UNI als Spannungsanzeige in Verwendung.

Kurze Nebenfrage: die Synchronisation des Wechselrichters mit dem aktuellen Verbrauch funktioniert super. Das heißt bei 200W Verbrauch speist der WR 200W ein. Wäre es aber auch irgendwie möglich sie Synchronisation vom Wert 0 auf eine Wert von zB 20 zu verschieben.  Soll heißen bei perfekter Synchronisierung kaufe ich 20W. Also 200W Verbrauch und 180W kommen vom WR. Will in der Nacht keinen negativen Wert haben und ins Netz einspeisen.

**Comment by KlausLi** [comment]
... Will in der Nacht keinen negativen Wert haben  ... 
den wirst du trotzdem haben , wann der kühlschrank ode sonstiges sich ausschaltet
das mit der verschobenen 0 punkt hatte ich schon mal drin , funzte damals nicht 
mal sehen wann das wieder reinkommt

**Comment by evoxievoxi** [comment]
...kurzfristig ist klar wenn ein Verbraucher abschaltet. Will einfach so wenig wie möglich ins minus rutschen.
Danke für den Tipp. Warum in die Ferne schweifen wenn das gute liegt so Nahe. Die einfachsten Lösungen sind oft bis besten.

Danke für die Unterstützung ;)
