### ISSUE TITLE
MQTT Problem mit 1.0.2.4

### ISSUE THREAD

**Issue by damark234** [KlausLi/Esp-Soyosource-Controller#16]
Moin,

habe von 1.0.2.2 auf 1.0.2.4 installiert. 

Nun habe ich das Problem das meine MQTT Übergabe vom Shelly minus Offset nicht mehr sauber eingespielt wird.
Habe dann Artefakte mit drin stehen die in der MQTT Nachricht nicht drin sind.

Also wenn ich z.B. 400 Watt Verbrauch habe dann habe zwischen drin 40000 Watt drin stehen. 
Kann auch nur ein Darstellungsfehler sein. Ich prüfe noch. 

Mit der 1.0.2.2 parallel wird alles sauber angezeigt. 

Grüße

**Comment by damark234** [comment]
Hab's er überschreibt immer die erste Stelle mit dem neuen Wert und setzt den Rest hinten dran. 

Also Wert 1: 150 Watt
Wert 2: 25 Watt 

Wird dann zu 2550 Watt

Erst mit dem ersten negativen Wert springt er dann zurück.

**Comment by KlausLi** [comment]
Kann ich nicht nachvollziehen !


Mit "er" meinst du deine Mqtt übergabefunktion an L1L2L3?
der esp übergibt ja keinen wert per mqtt an l1l2l3 !
wo hast du 40000 drin stehen ?

**Comment by KlausLi** [comment]
> Hab's er überschreibt immer die erste Stelle mit dem neuen Wert und setzt den Rest hinten dran.
> 
> Also Wert 1: 150 Watt Wert 2: 25 Watt
> 
> Wird dann zu 2550 Watt
> 
> Erst mit dem ersten negativen Wert springt er dann zurück. Macht auch die Regelung mit, also nicht nur ein Anzeigefehler.
Hallo 

Kann ich nicht nachvollziehen !

Mit "er" meinst du deine Mqtt übergabefunktion an L1L2L3?
der esp übergibt ja keinen wert per mqtt an l1l2l3 !
wo hast du 40000 drin stehen ?

**Comment by damark234** [comment]
Ich schicke meinen Verbrauch mit einem Offset per MQTT an den Soyo. Also auf das Topic vom Soyo. 

Die 40000 stehen im ESP bei Verbrauch drin und das setzt sich immer aus der geschrieben Rechnung heraus. Er ersetzt die erste Stelle mit dem neuen Wert und nutzt ihn für die Regelung. 

was meinst du damit ?
...MQTT Übergabe vom Shelly minus Offset nicht mehr sauber eingespielt wird...

nun ich kann es nicht mehr nutzen. Die Übergabe direkt aus dem Shelly geht und auch in der Variante 1.0.2.2 geht es weiterhin ohne Probleme. 

Ich flash mal einen Neuen morgen und schau ob das daran liegt.

**Comment by KlausLi** [comment]
> Ich schicke meinen Verbrauch mit einem Offset per MQTT an den Soyo. Also auf das Topic vom Soyo.
> 
> Die 40000 stehen im ESP bei Verbrauch drin und das setzt sich immer aus der geschrieben Rechnung heraus. Er ersetzt die erste Stelle mit dem neuen Wert und nutzt ihn für die Regelung.
> 
> was meinst du damit ? ...MQTT Übergabe vom Shelly minus Offset nicht mehr sauber eingespielt wird...
> 
> nun ich kann es nicht mehr nutzen. Die Übergabe direkt aus dem Shelly geht und auch in der Variante 1.0.2.2 geht es weiterhin ohne Probleme.
> 
> Ich flash mal einen Neuen morgen und schau ob das daran liegt.


hab an dieser funktion nie was geändert   mqttmessage -> str2long
das ist in integer also nix mit erster stelle nehmen oder so 

ja flash mal neu mit löschen
