### ISSUE TITLE
Belegung (Leiter, Neutral) des Netzanschluss

### ISSUE THREAD

**Issue by syssi** [KlausLi/Esp-Soyosource-Controller#17]
Hallo Klaus,

ich besitze zwei GTN1200. Wenn man sie öffnet und die Beschriftung auf der Platine (N, L) mit der Beschriftung der Klemmleiste (L, N) vergleicht, dann ist bei beiden Geräten der Netzanschluss (intern) verdreht angeschlossen. Gibt es trotzdem eine Belegung die zu bevorzugen ist?

Gruß Sebastian

**Comment by KlausLi** [comment]
Hi Sebastian

da muss ich ein bisschen ausholen für dieses Thema...

Ja die verdrehte anschluss weise von der Platine zur aussenklemme ist mir auch aufgefallen :-(, nicht schön.
Dem Soyo ist es in Verbindung mit dem Esp Limiter aber egal, wie rum.
Ich habe eine Kaltgerätebuchse verbaut an einem meiner Geräte da war es mir nicht wurscht, habs dann richtig rum angeschlossen!
Aber wann du genau bist müsstest du dann immer schauen daß der PhasenPin am Schukostecker in der Steckdose auch im Phasenloch drinsteckt.  Is aber dem Soyo wie gesagt egal!
Wie es beim original Klips Strommesslimiter aussieht kann ich  dir nicht sagen obs da dann was ausmacht wann du falsch rum die Phase dran hast, hatte den soyosource nie mit dem limiterklips in betrieb, obwohl vorhanden .

Ich sage daß deswegen, weil es bei meinen GTIL sun1000 die noch so rumliegen nicht egal ist wie rum ich einstecke wann die im limiter betrieb sind , DENN:
Die zeigen dann minus watt im Display an und regeln nicht obwohl der Limiterklips richtigrum( stromflussrichtung pfeil) verbaut ist. Schukostecker umdrehen in  der Steckdose und schon regelt der Sun wieder .

Wie du siehst , kein einfaches Thema bei den China Böllern ;-) 
Ps.: übrigens bei einem GTIL war es anfangs auch egal wie rum ich eingesteckt habe , bis ich die controllerplatine tauschte(war anfangs mal nötig) , is also scheints eine software geschichte ...

Mittlerweile tendiere ich auf jedenfall zum SOYO

Glückwunsch , du hast dich richtig entschieden  :-)

Fazit , zu deiner Frage ;-)  : lass die belegung so wie sie ist ausser du machst wie ich eine Kaltgerätebuchse rein

**Comment by syssi** [comment]
Danke für deine beruhigenden Worte und den Fleiß den du in dieses Projekt steckst!

**Comment by KlausLi** [comment]
> Danke für deine beruhigenden Worte und den Fleiß den du in dieses Projekt steckst!

Thank you very mucho grandisimo 
widerhören(mit e)
