### ISSUE TITLE
Unterschiedliche (geräteseitige) RS485-Wandler-Boards

### ISSUE THREAD

**Issue by syssi** [KlausLi/Esp-Soyosource-Controller#18]
Hi! Ich nutze diesen Platz um ein paar Infos abzuladen, welche hilfreich sein könnten, wenn man im Zukunft versucht unterschiedliche GTNs zu vergleichen oder vielleicht "stumme" GTNs (wieder) zum sprechen zu bewegen.

Meine zwei Geräte sind mit zwei unterschiedlichen RS485-Wandlern daher gekommen. Beide Geräte waren anfangs ansprechbar und haben auch das Status-Frame zurück geliefert. Der einfachere Wandler (`rs485-2.jpg`) hat leider bereits nach einem Tag die Arbeit eingestellt. Nehme ich den Wandler (`rs485-1.jpg`) aus dem anderen Inverter, so spricht das Gerät grundsätzlich noch mit mir. Ich sehe aktuell drei Wege das Problem zu lösen:

1. Neuen RS485-Wandler auf Aliexpress ordern. Das Produktbild zeigt die Version mit Spule (`rs485-1.jpg`)
2. Austausch des Wandlers gegen einen RS485-Modul welches man auch nutzen würde um den Inverter anzusprechen. Die Funktion von`J2` müsste man noch aus dem alten Board raus messen. `5V`, `GND`, `RX` und `TX` versteht sich von selbst.
3. Sich Gedanken darüber machen, ob die Pinne RX und TX direkt zum STM32 führen (3.3V TTL) und den ESP direkt verbinden. Hier habe frage ich mich, ob man die gemeinsame Masse zwischen ESP und Inverter vermeiden sollte und deshalb für zusätzliche Sicherheit immer den Umweg über RS485 macht.

Über Input bin ich dankbar.

![rs485-1](https://user-images.githubusercontent.com/2735933/156916533-8cdc5783-8840-43a7-9721-0172eda463d4.jpg)
![rs485-2](https://user-images.githubusercontent.com/2735933/156916534-95c88ae7-458d-4742-bea2-7ac15e57d2d0.jpg)

**Comment by KlausLi** [comment]
du kannst den wandler günstig nachbauen , hab video dazu gemacht , der nachbau ist dem günstigen ohne optokoppler nachempfunden 
Bauteile die du brauchst 
- rs485 ttl adapter (die version mit nur max485 ic)
- Widerstand und transistor 

hab a video zu gemacht , funktioniert einwandfrei
link kommt gleich

**Comment by KlausLi** [comment]
Ich würde den esp nicht direkt anschliessen... lass das max485 als schutz für beide seiten dazwischen

**Comment by syssi** [comment]
Danke! Mit deinen bereits gesammelten Infos komme ich bereits weiter. Ich mache den Issue an dieser Stelle zu in der Hoffnung, dass jeder ihn findet & kommentiert wer ihn Mal braucht.

**Comment by user0x01** [comment]
Ich habe heute ein wenig getestet und den rs485 weggelassen.
Der Soyo antwortet auch mit direkter Uartverbindung nicht, aber in soyosource_display: steht jetzt endlich bei Limiter on,
Verbunden habe ich das mit dem galvanischen Uart Trenner, ADUM1201: https://www.ebay.de/itm/234384336691

Da RX von Soyo nicht geht und der grüne Stecker nur 2 Leitungen hat, bräuchte man von dem vorhanden Board eigentlich nur den ersten Optokoppler mit der TX Leitung vom ESP zu schalten. Den B0505S herausnehmen und das rot schwarze Kabel auf den unteren Optokopler umhängen könnte vielleicht schon reichen.

Im Programm für den Limiter blockt die Weitergabe noch, aber da könnten die Daten auch über Mqtt von Espkolegen au dem Wlan stick besorgt werden.

**Comment by KlausLi** [comment]
mach ihn nicht kaputt , schick ihn mir wann du ihn nicht brauchst
