### ISSUE TITLE
Erweiterungs Anfrage: Vorgabewerte per MQTT empfangen

### ISSUE THREAD

**Issue by linuxdep** [KlausLi/Esp-Soyosource-Controller#19]
Hi,
super Projekt, danke. 
Ist es ggf. möglich das ganze zu erweitern um Werte nicht nur per Weboberfläche zu ändern, sonder auch per MQTT vorzugeben? Dann könnte man mittels übergeordnetem Automatisierungstool (Home Assistant, IO-Broker...) das ganze auch noch dynamisch anpassen.
Z.B. wenn der Akku durch die Sonne nie richtig voll wird (Frühjahr/Herbst) driften die Zellen ggf. zu weit auseinander. Wenn man darauf mittels MQTT die Einspeisung abschalten und/oder drosseln könnte um den Akku alle X Tage voll zu laden, wenn genug Sonne da ist.

**Comment by KlausLi** [comment]
f

> Hi, super Projekt, danke. Ist es ggf. möglich das ganze zu erweitern um Werte nicht nur per Weboberfläche zu ändern, sonder auch per MQTT vorzugeben? Dann könnte man mittels übergeordnetem Automatisierungstool (Home Assistant, IO-Broker...) das ganze auch noch dynamisch anpassen. Z.B. wenn der Akku durch die Sonne nie richtig voll wird (Frühjahr/Herbst) driften die Zellen ggf. zu weit auseinander. Wenn man darauf mittels MQTT die Einspeisung abschalten und/oder drosseln könnte um den Akku alle X Tage voll zu laden, wenn genug Sonne da ist.

funzt bereits
