### ISSUE TITLE
MQTT Fehlermeldung

### ISSUE THREAD

**Issue by babylongithub0815** [KlausLi/Esp-Soyosource-Controller#20]
Fehlermeldung in MQTT : Client [SOYO_42bd52] Message 220 deleted after 11 retries.

Im MQTT Pfad Soyosource/SOYO_42bd52/L1L2L3 wird der eingetragener Wert nicht im ESP übernommen. Die anderen Werte wie z.B. MaxPower funktionieren. Über die Urls  "Static L1L2L3" kann der Wert eingestellt werden (aber nicht über MQTT).

Software Version 1.0.2.4 Performance

**Comment by KlausLi** [comment]
das is doch ne Iobroker Meldung :-( 
wieso sucht keiner den Fehler wo er geschieht :_( 
Über http kannst du den wert auch übergeben

**Comment by babylongithub0815** [comment]
Servus,
mit IoBroker Meldung ist richtig. Alle MQTT Werte werden übernommen in MQTT nur nicht der "Static L1L2L3" Wert. Über die Urls/HTTP funktioniert es. Warum dieser Wert nicht übernommen wird verstehe ich noch nicht. Eventuell hat jemand ja eine Idee woran das liegen könnte. MfG
