### ISSUE TITLE
Spannungsversorgung instabil - mikro USB Anschluss eine Alternative ?

### ISSUE THREAD

**Issue by Rocky19911219** [KlausLi/Esp-Soyosource-Controller#21]
Hallo!

Vielen Dank für dieses wirklich geniale Projekt. 

Ich konnte das System(bis auf den WR) in Betrieb nehmen. 
Für die Spannungsversorgung des Wemos D1 Mini und RS485TTL Adapter, hatte ich günstig ein 220 V AC zu 3,3 V DC Netzteil gekauft und auch verkabelt. Irgendwie war das System extrem instabil und auch nach mehreren Stunde wurde es nicht besser.(WLAN Empfang war super, da Repeater etwa 20 cm entfernt ist) Ich habe daraufhin die Eingangspannung vom Netzteil gemessen und festgestellt, dass dort keine 3,3 V sondern 5 V anlagen. Okay, kein Wunder warum es möglicherweise nicht funktioniert. Nun habe ich es per mikro USB an einen Laptop geklemmt und das System läuft sofort und ohne Aussetzer. 

Nun meine Frage, kann ich beide Geräte per mikro USB an ein Steckernetzteil mit 1 A betreiben ? Ist das auf Dauer zu wenig bzw. sollte ich es normal per Kabel mit Strom versorgen ?

Ist noch geplant, dass man die Einspeisedifferenz einstellen kann ? Im Moment strebt das Gerät ja +- 0 W an soweit ich weiß ??

Können Sie mir bitte weiterhelfen ?

**Comment by KlausLi** [comment]
> Hallo!
> 
> Vielen Dank für dieses wirklich geniale Projekt.
> 
> Ich konnte das System(bis auf den WR) in Betrieb nehmen. Für die Spannungsversorgung des Wemos D1 Mini und RS485TTL Adapter, hatte ich günstig ein 220 V AC zu 3,3 V DC Netzteil gekauft und auch verkabelt. Irgendwie war das System extrem instabil und auch nach mehreren Stunde wurde es nicht besser.(WLAN Empfang war super, da Repeater etwa 20 cm entfernt ist) Ich habe daraufhin die Eingangspannung vom Netzteil gemessen und festgestellt, dass dort keine 3,3 V sondern 5 V anlagen. Okay, kein Wunder warum es möglicherweise nicht funktioniert. Nun habe ich es per mikro USB an einen Laptop geklemmt und das System läuft sofort und ohne Aussetzer.
> 
> Nun meine Frage, kann ich beide Geräte per mikro USB an ein Steckernetzteil mit 1 A betreiben ? Ist das auf Dauer zu wenig bzw. sollte ich es normal per Kabel mit Strom versorgen ?
> 
> Ist noch geplant, dass man die Einspeisedifferenz einstellen kann ? Im Moment strebt das Gerät ja +- 0 W an soweit ich weiß ??
> 
> Können Sie mir bitte weiterhelfen ?
Hallo Herr Balboa

5v an 3,3 volt eingang WOW was der Esp alles aushält :-)
steckernetzteil reicht denk ich , musst du hald probieren!

Was verstehst du unter Einspeisedifferenz ?

**Comment by Rothammel** [comment]
ich dachte auch schon an einen offset. könnte nützlich sein.

**Comment by Rocky19911219** [comment]
Okay, also USB Netzteil ist ausreichend. 

Ich habe noch gesehen, dass bei meinem Rs485 TTL Board ständig eine rote Lampe leuchtet. Ist das richtig ? 
Hab meinem soyo noch nicht, um zu testen, ob es geht. 

Mit Einspeisedifferenz meine ich, dass was am Stromzähler im Idealfall steht.Bei Nulleinspeisung wäre es 0 W.

Könnte man auch die Wartesekunden des Controllers verringern, damit dieser flinker auf Veränderungen reagiert kann ?

**Comment by KlausLi** [comment]
Könnte man auch die Wartesekunden des Controllers verringern
ja das geht 

Hab meinem soyo noch nicht
probiers erst mal aus wann du s hast
