### ISSUE TITLE
Hängt sich auf!

### ISSUE THREAD

**Issue by Master2k7** [KlausLi/Esp-Soyosource-Controller#22]
Hallo, benutzte die aktuelle Version auf einem Wemos d1 pro. Es funktioniert alles so weit ganz gut. Daten kommen vom einem tasmota Wemos am Stromzähler die über iobroker zum Soyo Controller gehen per mqtt. Leider muss ich alle paar Tage den Soyo Controller Neustarten da der aktuelle Verbrauchswert kleben bleibt. Woran kann das liegen?

**Comment by KlausLi** [comment]
> Hallo, benutzte die aktuelle Version auf einem Wemos d1 pro. Es funktioniert alles so weit ganz gut. Daten kommen vom einem tasmota Wemos am Stromzähler die über iobroker zum Soyo Controller gehen per mqtt. Leider muss ich alle paar Tage den Soyo Controller Neustarten da der aktuelle Verbrauchswert kleben bleibt. Woran kann das liegen?

Es gibt da schon ein Problem mit ner libary die ich verwende aber nicht in verbindung mit dem soyo controller ... bisher
1. wie oft sendest du die Werte ?
2. alles restliche funktioniert noch , wie ich vermute , webinterface etc...
3. Kannst du testhalber umswitschen auf httpinterface
http://192.168.xxx.xxx/L1L2L3Auto?Value=200.66
teste es mal eine woche lang , das sollte ausfallfrei sein, wobei ich bei mqtt subscribe am soyo nie probleme hatte , naja wir werdens ja sehen!
4. Ansonsten , hast du geprüft ob deine werte auch gesendet werden  mit z.B. MqttFX unter windows?

ansonsten der Esp startet selbst "hi und da" neu , ist aber in Ordnung
