### ISSUE TITLE
Static Wert bleibt nicht dauerhaft gesetzt

### ISSUE THREAD

**Issue by crytylus** [KlausLi/Esp-Soyosource-Controller#24]
Hi Klaus,
ich betreibe meinen Soyo gerade als PV Wechselrichter.
Allerdings hört nach ein paar Tagen auf zu produzieren, ich kann ihn aber wieder aktivieren über RS485.
(Der Fehler tritt allerdings auf, egal ob RS485 verbunden ist oder nicht)

Also quickfix, einfach 1200W Static in der Webgui gesetzt. Dieser Wert verschwindet nach einer Weile, und dann ist wieder Schluss mit Produktion.
Jetzt feuer ich alle paar Sekunden 1200W per Auto-Mqtt, das läuft erstmal.

Aber wieso verschwindet der gesetzte Static Wert aus Zeile L1L2L3? Kann der Soyo das beinflussen? Der Fehler tritt ja auch ohne RS485 auf...

Hab ich meinen Soyo jetzt versaut und er kann nie mehr ohne RS485 Kommando?
Danke, freu mich auf den JK BMS Controller!

**Comment by KlausLi** [comment]
... Wert verschwindet ... 
der esp wird, weswegen auch immer,  neugestartet haben 
soweit ichs verstanden habe willst du nicht Nulleinspeise regeln also ist auto... die falsche betriebsart
Abhilfe : über http static interface alle min  den wert 100 für 100w senden 
dann bist du im grünen bereich

Das mit dem versaut versteh ich nicht , da bin ich sowieso der falsche Ansprechpartner.
JK *würg

**Comment by crytylus** [comment]
Das Problem lag nicht beim Soyo, sondern beim Sonoff Pow R2, der davon geschaltet war....

**Comment by KlausLi** [comment]
> Das Problem lag nicht beim Soyo, sondern beim Sonoff Pow R2, der davon geschaltet war....

geht mir sicher auch so ,der Wald hat viele Bäume , gegen jeden muss man erst mal gerannt sein :-), so sieht bei mir die lernphase  aus :-)
Danke für dein Rückmeldung :-)
