### ISSUE TITLE
Kein Soyo_ WLAN nach flashen mit v1.0.2.6

### ISSUE THREAD

**Issue by crytylus** [KlausLi/Esp-Soyosource-Controller#25]
Hello again,
hab zwei frische D1mini erst mit blank 4MB und dann v1.0.2.6 geflasht, kein WLAN AP.
Wenn ich dann 1.0.2.5 flashe ist der AP wie gewohnt da...

**Comment by KlausLi** [comment]
ich glaub du willst mich testen :-( 
habs nun auch mit neuem d1 versucht und tasmotizer incl erase (da sparst du dir den extra blank gang)
FUNZT!

**Comment by crytylus** [comment]
Ach shit, sorry. Das Bin-file war unvollständig. Jetzt funzts!

**Comment by KlausLi** [comment]
> Ach shit, sorry. Das Bin-file war unvollständig. Jetzt funzts!

kimmd davon wann da bierpegel ned stimmd ! awa jetzt :-)
vielen Dank für deine Tests, hättest ja auch Recht haben können ! 
lg Klaus
