### ISSUE TITLE
AC WattsOut + NotAus

### ISSUE THREAD

**Issue by elzershark** [KlausLi/Esp-Soyosource-Controller#27]
Es gibt ja AC WattsOut.
Den Verstehe ich nicht ganz.
Wenn der L1L2L3 geändert wird oder man klickt auf die Buttons von Soyo's dann wird der Wert immer höher.
Erst bei NotAus an/aus machen, steht da wieder 0 drin.
Vieleicht noch n Bug?
Muss aber sagen, hab das ohne die Verbindung zum Wechselrichter getestet. Kabel steckt nicht im RS485 drin vom Wechselrichter.
P.S.
Hab ein wenig gebraucht.. (iobroker - MQTT) was der Wert sein muss für NotAus (on/off)
Glaub das steht nicht in der Anleitung. Oder zusätzlich Programmieren für     true/false     0/1     0/100
Oder vieleicht gleich true/false machen. on/off ist super selten, das solche Werte genutz werden

**Comment by KlausLi** [comment]
> Es gibt ja AC WattsOut. Den Verstehe ich nicht ganz. Wenn der L1L2L3 geändert wird oder man klickt auf die Buttons von Soyo's dann wird der Wert immer höher. Erst bei NotAus an/aus machen, steht da wieder 0 drin. Vieleicht noch n Bug? Muss aber sagen, hab das ohne die Verbindung zum Wechselrichter getestet. Kabel steckt nicht im RS485 drin vom Wechselrichter. P.S. Hab ein wenig gebraucht.. (iobroker - MQTT) was der Wert sein muss für NotAus (on/off) Glaub das steht nicht in der Anleitung. Oder zusätzlich Programmieren für true/false 0/1 0/100 Oder vieleicht gleich true/false machen. on/off ist super selten, das solche Werte genutz werden

..ein wenig gebraucht... gibt ja nich viele wirklich viele Alternativen zu an / aus ;-)

... Kabel steckt nicht im RS485 
TOP
Der soyosource controller unterstützt aber kein wireless Rs485

**Comment by KlausLi** [comment]
> Es gibt ja AC WattsOut. Den Verstehe ich nicht ganz. Wenn der L1L2L3 geändert wird oder man klickt auf die Buttons von Soyo's dann wird der Wert immer höher. Erst bei NotAus an/aus machen, steht da wieder 0 drin. Vieleicht noch n Bug? Muss aber sagen, hab das ohne die Verbindung zum Wechselrichter getestet. Kabel steckt nicht im RS485 drin vom Wechselrichter. P.S. Hab ein wenig gebraucht.. (iobroker - MQTT) was der Wert sein muss für NotAus (on/off) Glaub das steht nicht in der Anleitung. Oder zusätzlich Programmieren für true/false 0/1 0/100 Oder vieleicht gleich true/false machen. on/off ist super selten, das solche Werte genutz werden

Wer den Wert für Notaus noch in die Readme reinschreiben , wann nicht schon passiert

**Comment by elzershark** [comment]
hi, ne, so mein ich das nicht. Auf der Weboberfläche von deinem Tool. Dort steht doch AC WattsOut. Wenn man mit den Buttons "rumspielt" (die Buttons von Soyo auf der Webseite) steigt der Wert immer höher von  AC WattsOut.

**Comment by KlausLi** [comment]
Geht bis 9000 es meinst du das?Am 11.05.2022 14:24 schrieb Elzershark ***@***.***>:

hi, ne, so mein ich das nicht. Auf der Weboberfläche von deinem Tool. Dort steht doch AC WattsOut. Wenn man mit den Buttons "rumspielt" (die Buttons von Soyo auf der Webseite) steigt der Wert immer höher von  AC WattsOut.

**Comment by elzershark** [comment]
hm, ne.. das funzt leider nicht. Werte +1 -1 funzen manchmal, aber nicht immer. Gleiche werte können nicht eingesetzt werden.. Schade

**Comment by KlausLi** [comment]
Kannst du jetzt lassen bitte...schade?Am 11.05.2022 15:56 schrieb Elzershark ***@***.***>:

hm, ne.. das funzt leider nicht. Werte +1 -1 funzen manchmal, aber nicht immer. Gleiche werte können nicht eingesetzt werden.. Schade
