### ISSUE TITLE
kein Issue, aber eine Frage

### ISSUE THREAD

**Issue by Rothammel** [KlausLi/Esp-Soyosource-Controller#29]
Klaus, kann man einen wifi soyo eigentlich über Wlan steuern? hast du da Infos für mich?

**Comment by KlausLi** [comment]
> Klaus, kann man einen wifi soyo eigentlich über Wlan steuern? hast du da Infos für mich?

Ich hab die Frage studiert und jetzt ein paar mal von der Formulierung her im Kopf gedreht und hab dann auch den Monitor gedreht, nix...
BrainShutdown!, ich frage deswegen nach : Was meinst du damit ?
:-)

**Comment by Rothammel** [comment]
hihi, hy Klaus, ich baue gerade den ESP mit RS485 zusammen und dabei kam in mir die Frage hoch, ob man nicht auch über das originale WIFI Modul steuern kann? also so tun als ob man eine China App wäre

**Comment by KlausLi** [comment]
> hihi, hy Klaus, ich baue gerade den ESP mit RS485 zusammen und dabei kam in mir die Frage hoch, ob man nicht auch über das originale WIFI Modul steuern kann? also so tun als ob man eine China App wäre

das kann ich mir nicht vorstellen , daß sich die China Mädels sich dazu Zeit genommen haben ne schnittstelle einzubauen oder zu bedienen (mir ist nichts bekannt) , wann du dir das SOYO wifi menu ansiehst ... nööö.... die waren mit Farbenauswahl beschäftigt :-)

**Comment by KlausLi** [comment]
> ändere

und wenn ich den nun alle Sekunde ändere...
->is dein eeprom hin!

**Comment by Rothammel** [comment]
> > ändere
> 
> und wenn ich den nun alle Sekunde ändere... ->is dein eeprom hin!

genau, also ich hole jetzt den Lötkolben und du kannst derweile den issue zu machen - danke dir für deine Arbei

**Comment by KlausLi** [comment]
> eeprom

Jawoll chef 
:-) bis dann
