### ISSUE TITLE
Neue Firmware  , Problem mit Auslesen

### ISSUE THREAD

**Issue by helgeschneider** [KlausLi/Esp-Soyosource-Controller#32]
Die neue Firmware STC8-2022-218 hat laut https://secondlifestorage.com/index.php?threads/limiter-inverter-with-rs485-load-setting.7631/post-82148 Probleme mit den Statusmeldungen

**Comment by KlausLi** [comment]
du kannst das ja selber testen mit usb rs485 schick die 24 und 7 *0 bytes  und schau ob was kommt
wann nicht , pech gehabt
versuch ein anderes rs485 modul und einen nativen esp12

**Comment by B230FK** [comment]
Ich habe auf zwei Soyos diese Firmware und beide melden dem ESP die DC Werte zurück.

**Comment by syssi** [comment]
@B230FK Sind es Soyos mit oder ohne Display (WiFi Dongle)?
