### ISSUE TITLE
MQTT Info "Status(23)" not valid

### ISSUE THREAD

**Issue by alexandergeiler** [KlausLi/Esp-Soyosource-Controller#34]
Hi,

I build a ESP Soyosource Controller and it is working fine.
I can control my Soyosource inverter and I see, that the ESP is sending it´s values to the MQTT AllJsonData Topic but not to the Info topic.

Any idea´s what I can do?
![Info](https://user-images.githubusercontent.com/4689177/173995367-679adc9f-c07c-4b00-9b1f-15966fc44a0e.png)

**Comment by KlausLi** [comment]
that is the start message in ifo topic, what is the question?
