### ISSUE TITLE
FeatureRequest, change via URL the Controller Mode

### ISSUE THREAD

**Issue by alexandergeiler** [KlausLi/Esp-Soyosource-Controller#35]
Hi,

I build a ESp-Soyosource-Controller and I am using it with a Pylontech US 3000 batterie.
I got my L1L2L3 via MQTT from my Iskra powermeter and it is working as expected.

When the battery is running low (e.g. little sun) I would like to reduce the power massively.

If I try to open http://192.168.185.58/L1L2L3Static?Value=50
![ControllerMode wrong](https://user-images.githubusercontent.com/4689177/173996158-f38abda0-b38e-4a10-8fd3-9e1fa143e610.png)
I get the message that the controller mode is wrong.

Clear, I have set the controller mode to "Auto Subscribe L1L2L3"
![ControllerMode](https://user-images.githubusercontent.com/4689177/173996682-7070ef42-6bad-4b2a-bff8-7191dd49f4e0.png)

How can I change the controller mode via URL to: Static HttpInterface/WebGui?

**Comment by KlausLi** [comment]
Die Betriebsarten siehst du im Http quellcode iim browser der esp web gui unter value bei den optionen

Static :
http://192.168.xxx.xxx/System?ControllerMode=StaticHttpInterface&ShellyIP=0.0.0.0&L1=true&L2=true&L3=true&Topic=test

autohttpclient:
http://192.168.xxx.xxx/System?ControllerMode=AutoShellyHttpClient&ShellyIP=192.168.1.21&L1=true&L2=true&L3=true&Topic=test


gefolgt von
http://192.168.xxx.xxx/reset (muss du ausprobieren ob nötig...)
