### ISSUE TITLE
Use Soyosource with Battery and Controller to Limit power

### ISSUE THREAD

**Issue by alexandergeiler** [KlausLi/Esp-Soyosource-Controller#37]
Hi,
I am using a Soyosource GTW 1200W inverter with a Pylontech US 3000 battery.
I get my power values via MQTT from my Iskar power meter and it is working fine.

Acording to my knowledge, I should set the inverter  to "Bat Mode Enable=Y" to disable the internal MPPT.
If I set it to Y, and change afterwards the "Auto Limit Power" value to yes it will automatilly change the Bat Mode Enable back to N.

Has anyone else a Soyosource on a battery and can confirm this?
Then a dynamic limiting via MQTT would unfortunately not work.

https://user-images.githubusercontent.com/4689177/176870920-8b0c8eba-2e03-4006-9486-c1dc393a79a5.mp4

**Comment by KlausLi** [comment]
you have 3 settings
![2022-07-01 16_49_57-1200W 1000W Solar Grid Tie Inverter DC24V 48V 72V 96V zu AC110V AC230V mit Limit](https://user-images.githubusercontent.com/32024629/176918765-0aff98ec-a7a9-47ac-9291-7d37cd9fd3b3.png)
