### ISSUE TITLE
Soyo sägt - Regelung "überschwingt"

### ISSUE THREAD

**Issue by B230FK** [KlausLi/Esp-Soyosource-Controller#39]
Hallo zusammen,

ich habe heute meinen Shelly 3EM verbaut und einen SoyoLimiter fertiggebaut und angeschlossen - funktioniert auch soweit.
Der Controller zeigt die DC Daten des Soyo an genau wie auch die aktuelle Leistung auf der ausgewählten Phase L3 und regelt entsprechend... mehr oder weniger...

Zum Zeitpunkt des Tests war eine Last von ca. 150W auf L3 bereits aktiv (Fernseher).
Im Shelly blieb die Anzeige auch recht konstant, nur wenige Watt schwankung.

Nun zum Problem: Sobald der Soyo startete bekam er quasi in Endlosschleife einen passenden, dann einen zu hohen, dann 0W Sollwert.

Für mich sieht das so aus als würde die Laufzeit der Signale bzw. die reaktionszeit des Soyo zu langsam sein?
Der Controller verdoppelt alle ca. 3 Sekunden das Sollsignal.
Bis der Soyo den ersten Befehl von 150W umgesetzt hat, was ja genau passen würde, hat der Controller schon auf 300W erhöht. - Dann kommt vom Shelly der Wert -150W woraufhin der Controller dem Soyo befiehlt auf 0W zu gehen. 
Shelly 150W - Controller 150W - Soyo 150W - Controller erhöht auf 300W - Soyo 300W - Shelly -150W

Ist der Controller einfach zu ungeduldig? Kann man da die Auslesegeschwindigkeit des Shelly erhöhen, oder den Zeitraum bis ein neuer Befehl zum Soyo gesendet wird verlangsamen um diesen Zustand zu verhindern? So pendelt sich leider nichts ein, sondern Springt die ganze Zeit wie beschrieben hin- und her.

Wlan Empfang stand bei -60. Test fand nur ca. 2m vom AP entfernt statt. Der Shelly ist nichtmal 1m vom AP entfernt.

Gibts da eine Möglichkeit, wie ich das hier vor Ort alleine lösen kann oder ist evtl eine Softwareanpassung erforderlich?

**Comment by KlausLi** [comment]
beim starten is es normal , falls der esp erster ist der da ist muss er erst mal runter regeln
kannst du vernachlässigen da du ja eh nicht ständig neustartest sondern  das teil durchläuft

**Comment by KlausLi** [comment]
ich denke du machst nen fehler 
du hast mehrere limiter zur gleichen zeit angeschlossen
oder 
2 soyo an einem esp und 1 soyo am esp eingestellt
das sind erheerende dinge 
oder du sendest die L1L2L3 signale  in dieser warnblinker art
wann nicht 
dann weiss ich auch nicht weiter , zu wenig info, zuviel raten
::-(

**Comment by B230FK** [comment]
Ich habe einen Limiter zur Zeit an genau einem Soyo angeschlossen. Am Soyo ist die IP des Shelly hinterlegt, und L3 ausgewählt. An L3 hängt auch der Soyo.
Sag mir welche weiteren Infos du brauchst dann bekommst du sie.

Jedenfalls ist das Problem für mich noch lange nicht gelöst...

**Comment by syssi** [comment]
Ich möchte ein paar Kleinigkeiten mit in den Topf werfen in der Hoffnung zur Lösung des Problems beizutragen und nicht noch weitere Verwirrung zu stiften:

Ich wüsste gerne, was der Esp-Soyosource-Controller mit dem Werten vom Shell macht. Werden sie 1:1 uns zeitnah als RS485-Nachricht an den Soyosource geschickt oder werden sie gesammelt, gemittelt und gemächlich an den Soyosource weitergegeben? Angenommen Shelly hat die Update-Frequenz erhöht, dann hat der Soyo keine Zeit mehr sauber hochzufahren. Er braucht etwas Zeit bis man ihn mit der nächsten Instruktion versorgen kann. Er soll dem gemeldeten Verbrauch nämlich hinterher eilen und nicht vorne weg laufen.

**Comment by KlausLi** [comment]
alter schwede das läuft bei mir nun 24/7 1 Jahr lang fehlerfrei , was für ne waste of time here ...
Ich hab die möglichkeiten erwähnt die das auslösen können 0-150-50...
